services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: amopoint_test_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
    restart: unless-stopped